// src/constants/locationOptions.ts

export const departamentos = [
  { label: "Otro (Para extranjeros)", value: "00" },
  { label: "Ahuachapán", value: "01" },
  { label: "Santa Ana", value: "02" },
  { label: "Sonsonate", value: "03" },
  { label: "Chalatenango", value: "04" },
  { label: "La Libertad", value: "05" },
  { label: "San Salvador", value: "06" },
  { label: "Cuscatlán", value: "07" },
  { label: "La Paz", value: "08" },
  { label: "Cabañas", value: "09" },
  { label: "San Vicente", value: "10" },
  { label: "Usulután", value: "11" },
  { label: "San Miguel", value: "12" },
  { label: "Morazán", value: "13" },
  { label: "La Unión", value: "14" },
];

export const municipios = [
  { label: "AHUACHAPAN NORTE", value: "13", departamento: "01" },
  { label: "AHUACHAPAN CENTRO", value: "14", departamento: "01" },
  { label: "AHUACHAPAN SUR", value: "15", departamento: "01" },
  { label: "SANTA ANA NORTE", value: "14", departamento: "02" },
  { label: "SANTA ANA CENTRO", value: "15", departamento: "02" },
  { label: "SANTA ANA ESTE", value: "16", departamento: "02" },
  { label: "SANTA ANA OESTE", value: "17", departamento: "02" },
  { label: "SONSONATE NORTE", value: "17", departamento: "03" },
  { label: "SONSONATE CENTRO", value: "18", departamento: "03" },
  { label: "SONSONATE ESTE", value: "19", departamento: "03" },
  { label: "SONSONATE OESTE", value: "20", departamento: "03" },
  { label: "CHALATENANGO NORTE", value: "34", departamento: "04" },
  { label: "CHALATENANGO CENTRO", value: "35", departamento: "04" },
  { label: "CHALATENANGO SUR", value: "36", departamento: "04" },
  { label: "LA LIBERTAD NORTE", value: "23", departamento: "05" },
  { label: "LA LIBERTAD CENTRO", value: "24", departamento: "05" },
  { label: "LA LIBERTAD OESTE", value: "25", departamento: "05" },
  { label: "LA LIBERTAD ESTE", value: "26", departamento: "05" },
  { label: "LA LIBERTAD COSTA", value: "27", departamento: "05" },
  { label: "LA LIBERTAD SUR", value: "28", departamento: "05" },
  { label: "SAN SALVADOR NORTE", value: "20", departamento: "06" },
  { label: "SAN SALVADOR OESTE", value: "21", departamento: "06" },
  { label: "SAN SALVADOR ESTE", value: "22", departamento: "06" },
  { label: "SAN SALVADOR CENTRO", value: "23", departamento: "06" },
  { label: "SAN SALVADOR SUR", value: "24", departamento: "06" },
  { label: "CUSCATLAN NORTE", value: "17", departamento: "07" },
  { label: "CUSCATLAN SUR", value: "18", departamento: "07" },
  { label: "LA PAZ OESTE", value: "23", departamento: "08" },
  { label: "LA PAZ CENTRO", value: "24", departamento: "08" },
  { label: "LA PAZ ESTE", value: "25", departamento: "08" },
  { label: "CABAÑAS OESTE", value: "10", departamento: "09" },
  { label: "CABAÑAS ESTE", value: "11", departamento: "09" },
  { label: "SAN VICENTE NORTE", value: "14", departamento: "10" },
  { label: "SAN VICENTE SUR", value: "15", departamento: "10" },
  { label: "USULUTAN NORTE", value: "24", departamento: "11" },
  { label: "USULUTAN ESTE", value: "25", departamento: "11" },
  { label: "USULUTAN OESTE", value: "26", departamento: "11" },
  { label: "SAN MIGUEL NORTE", value: "21", departamento: "12" },
  { label: "SAN MIGUEL CENTRO", value: "22", departamento: "12" },
  { label: "SAN MIGUEL OESTE", value: "23", departamento: "12" },
  { label: "MORAZAN NORTE", value: "27", departamento: "13" },
  { label: "MORAZAN SUR", value: "28", departamento: "13" },
  { label: "LA UNION NORTE", value: "19", departamento: "14" },
  { label: "LA UNION SUR", value: "20", departamento: "14" },
];
